#!/bin/bash
# GRASPO e2e matrix runner — auto-generated by generate_matrix.py
# Usage: bash run_matrix.sh <output_dir>
# No set -e: single test failure does not stop the matrix

set -u  # fail on undefined variables

if [ $# -lt 1 ]; then
  echo "Usage: $0 <output_dir>"
  echo "  output_dir: directory to store per-test logs and outputs"
  echo "  Example: $0 /data/user/e2e-results"
  exit 1
fi

OUTDIR="$(realpath "$1")"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

IMG=graspo:0.29.0
MDIR9=/data/user/models
MDIR27=/data/user/vllm
SDIR="$PROJ_DIR/samples"
MOUNTS="-v $MDIR9:/data/user/models -v $MDIR27:/data/user/vllm -v $SDIR:/workspace/graspo/samples"
TIMEOUT=1200

mkdir -p "$OUTDIR"

SUMMARY="$OUTDIR/summary.txt"
echo "=== GRASPO E2E Matrix $(date) ===" | tee "$SUMMARY"
echo "Image: $IMG" | tee -a "$SUMMARY"
echo "Timeout: $TIMEOUT s per test" | tee -a "$SUMMARY"
echo "Output: $OUTDIR" | tee -a "$SUMMARY"
echo "Tests: 56" | tee -a "$SUMMARY"
echo "" | tee -a "$SUMMARY"

PASS=0; FAIL=0; TIME=0

run_one() {
  local name="$1"; local cfg="$2"; local gpus="$3"

  local test_dir="$OUTDIR/$name"
  mkdir -p "$test_dir"
  local log="$test_dir/log.txt"

  echo "[$(date +%H:%M:%S)] ▶ $name" | tee -a "$SUMMARY"

  docker rm -f "e2e-${name}" 2>/dev/null || true

  local nccl_env=""
  if [ "$gpus" != "0" ]; then
    nccl_env="-e NCCL_P2P_DISABLE=1"
  fi

  local output_mount="-v $test_dir:/workspace/outputs"

  timeout $TIMEOUT docker run --rm --name "e2e-${name}" \
    --gpus "\"device=${gpus}\"" \
    --ipc=host --shm-size=16g \
    -e PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
    $nccl_env \
    $MOUNTS \
    $output_mount \
    $IMG launch --config "$cfg" > "$log" 2>&1
  local rc=$?

  docker rm -f "e2e-${name}" 2>/dev/null || true

  if [ $rc -eq 0 ]; then
    echo "  ✅ $name PASS" | tee -a "$SUMMARY"
    PASS=$((PASS + 1))
  elif [ $rc -eq 124 ]; then
    echo "  ⏰ $name TIMEOUT" | tee -a "$SUMMARY"
    TIME=$((TIME + 1))
  else
    echo "  ❌ $name FAIL (rc=$rc)" | tee -a "$SUMMARY"
    FAIL=$((FAIL + 1))
    echo "  Last 5 log lines:" | tee -a "$SUMMARY"
    grep -v "MEM rank" "$log" 2>/dev/null | tail -5 | sed "s/^/    /" | tee -a "$SUMMARY"
  fi
}

echo '' | tee -a "$SUMMARY"
echo '===== RL (28 tests) =====' | tee -a "$SUMMARY"
echo '' | tee -a "$SUMMARY"
echo '--- 9B (14 tests) ---' | tee -a "$SUMMARY"
run_one 9b_rl_w1_tp1_dp1_pp1_sp0 "samples/configs/matrix/9b_rl_w1_tp1_dp1_pp1_sp0.yaml" "0"
run_one 9b_rl_w2_tp1_dp1_pp2_sp0 "samples/configs/matrix/9b_rl_w2_tp1_dp1_pp2_sp0.yaml" "0,1"
run_one 9b_rl_w2_tp1_dp2_pp1_sp0 "samples/configs/matrix/9b_rl_w2_tp1_dp2_pp1_sp0.yaml" "0,1"
run_one 9b_rl_w2_tp2_dp1_pp1_sp0 "samples/configs/matrix/9b_rl_w2_tp2_dp1_pp1_sp0.yaml" "0,1"
run_one 9b_rl_w2_tp2_dp1_pp1_sp1 "samples/configs/matrix/9b_rl_w2_tp2_dp1_pp1_sp1.yaml" "0,1"
run_one 9b_rl_w4_tp1_dp1_pp4_sp0 "samples/configs/matrix/9b_rl_w4_tp1_dp1_pp4_sp0.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp1_dp2_pp2_sp0 "samples/configs/matrix/9b_rl_w4_tp1_dp2_pp2_sp0.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp1_dp4_pp1_sp0 "samples/configs/matrix/9b_rl_w4_tp1_dp4_pp1_sp0.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp2_dp1_pp2_sp0 "samples/configs/matrix/9b_rl_w4_tp2_dp1_pp2_sp0.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp2_dp1_pp2_sp1 "samples/configs/matrix/9b_rl_w4_tp2_dp1_pp2_sp1.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp2_dp2_pp1_sp0 "samples/configs/matrix/9b_rl_w4_tp2_dp2_pp1_sp0.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp2_dp2_pp1_sp1 "samples/configs/matrix/9b_rl_w4_tp2_dp2_pp1_sp1.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp4_dp1_pp1_sp0 "samples/configs/matrix/9b_rl_w4_tp4_dp1_pp1_sp0.yaml" "0,1,2,3"
run_one 9b_rl_w4_tp4_dp1_pp1_sp1 "samples/configs/matrix/9b_rl_w4_tp4_dp1_pp1_sp1.yaml" "0,1,2,3"
echo '' | tee -a "$SUMMARY"
echo '--- 27B (14 tests) ---' | tee -a "$SUMMARY"
run_one 27b_rl_w1_tp1_dp1_pp1_sp0 "samples/configs/matrix/27b_rl_w1_tp1_dp1_pp1_sp0.yaml" "0"
run_one 27b_rl_w2_tp1_dp1_pp2_sp0 "samples/configs/matrix/27b_rl_w2_tp1_dp1_pp2_sp0.yaml" "0,1"
run_one 27b_rl_w2_tp1_dp2_pp1_sp0 "samples/configs/matrix/27b_rl_w2_tp1_dp2_pp1_sp0.yaml" "0,1"
run_one 27b_rl_w2_tp2_dp1_pp1_sp0 "samples/configs/matrix/27b_rl_w2_tp2_dp1_pp1_sp0.yaml" "0,1"
run_one 27b_rl_w2_tp2_dp1_pp1_sp1 "samples/configs/matrix/27b_rl_w2_tp2_dp1_pp1_sp1.yaml" "0,1"
run_one 27b_rl_w4_tp1_dp1_pp4_sp0 "samples/configs/matrix/27b_rl_w4_tp1_dp1_pp4_sp0.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp1_dp2_pp2_sp0 "samples/configs/matrix/27b_rl_w4_tp1_dp2_pp2_sp0.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp1_dp4_pp1_sp0 "samples/configs/matrix/27b_rl_w4_tp1_dp4_pp1_sp0.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp2_dp1_pp2_sp0 "samples/configs/matrix/27b_rl_w4_tp2_dp1_pp2_sp0.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp2_dp1_pp2_sp1 "samples/configs/matrix/27b_rl_w4_tp2_dp1_pp2_sp1.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp2_dp2_pp1_sp0 "samples/configs/matrix/27b_rl_w4_tp2_dp2_pp1_sp0.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp2_dp2_pp1_sp1 "samples/configs/matrix/27b_rl_w4_tp2_dp2_pp1_sp1.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp4_dp1_pp1_sp0 "samples/configs/matrix/27b_rl_w4_tp4_dp1_pp1_sp0.yaml" "0,1,2,3"
run_one 27b_rl_w4_tp4_dp1_pp1_sp1 "samples/configs/matrix/27b_rl_w4_tp4_dp1_pp1_sp1.yaml" "0,1,2,3"
echo '' | tee -a "$SUMMARY"
echo '===== SFT (28 tests) =====' | tee -a "$SUMMARY"
echo '' | tee -a "$SUMMARY"
echo '--- 9B (14 tests) ---' | tee -a "$SUMMARY"
run_one 9b_sft_w1_tp1_dp1_pp1_sp0 "samples/configs/matrix/9b_sft_w1_tp1_dp1_pp1_sp0.yaml" "0"
run_one 9b_sft_w2_tp1_dp1_pp2_sp0 "samples/configs/matrix/9b_sft_w2_tp1_dp1_pp2_sp0.yaml" "0,1"
run_one 9b_sft_w2_tp1_dp2_pp1_sp0 "samples/configs/matrix/9b_sft_w2_tp1_dp2_pp1_sp0.yaml" "0,1"
run_one 9b_sft_w2_tp2_dp1_pp1_sp0 "samples/configs/matrix/9b_sft_w2_tp2_dp1_pp1_sp0.yaml" "0,1"
run_one 9b_sft_w2_tp2_dp1_pp1_sp1 "samples/configs/matrix/9b_sft_w2_tp2_dp1_pp1_sp1.yaml" "0,1"
run_one 9b_sft_w4_tp1_dp1_pp4_sp0 "samples/configs/matrix/9b_sft_w4_tp1_dp1_pp4_sp0.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp1_dp2_pp2_sp0 "samples/configs/matrix/9b_sft_w4_tp1_dp2_pp2_sp0.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp1_dp4_pp1_sp0 "samples/configs/matrix/9b_sft_w4_tp1_dp4_pp1_sp0.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp2_dp1_pp2_sp0 "samples/configs/matrix/9b_sft_w4_tp2_dp1_pp2_sp0.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp2_dp1_pp2_sp1 "samples/configs/matrix/9b_sft_w4_tp2_dp1_pp2_sp1.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp2_dp2_pp1_sp0 "samples/configs/matrix/9b_sft_w4_tp2_dp2_pp1_sp0.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp2_dp2_pp1_sp1 "samples/configs/matrix/9b_sft_w4_tp2_dp2_pp1_sp1.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp4_dp1_pp1_sp0 "samples/configs/matrix/9b_sft_w4_tp4_dp1_pp1_sp0.yaml" "0,1,2,3"
run_one 9b_sft_w4_tp4_dp1_pp1_sp1 "samples/configs/matrix/9b_sft_w4_tp4_dp1_pp1_sp1.yaml" "0,1,2,3"
echo '' | tee -a "$SUMMARY"
echo '--- 27B (14 tests) ---' | tee -a "$SUMMARY"
run_one 27b_sft_w1_tp1_dp1_pp1_sp0 "samples/configs/matrix/27b_sft_w1_tp1_dp1_pp1_sp0.yaml" "0"
run_one 27b_sft_w2_tp1_dp1_pp2_sp0 "samples/configs/matrix/27b_sft_w2_tp1_dp1_pp2_sp0.yaml" "0,1"
run_one 27b_sft_w2_tp1_dp2_pp1_sp0 "samples/configs/matrix/27b_sft_w2_tp1_dp2_pp1_sp0.yaml" "0,1"
run_one 27b_sft_w2_tp2_dp1_pp1_sp0 "samples/configs/matrix/27b_sft_w2_tp2_dp1_pp1_sp0.yaml" "0,1"
run_one 27b_sft_w2_tp2_dp1_pp1_sp1 "samples/configs/matrix/27b_sft_w2_tp2_dp1_pp1_sp1.yaml" "0,1"
run_one 27b_sft_w4_tp1_dp1_pp4_sp0 "samples/configs/matrix/27b_sft_w4_tp1_dp1_pp4_sp0.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp1_dp2_pp2_sp0 "samples/configs/matrix/27b_sft_w4_tp1_dp2_pp2_sp0.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp1_dp4_pp1_sp0 "samples/configs/matrix/27b_sft_w4_tp1_dp4_pp1_sp0.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp2_dp1_pp2_sp0 "samples/configs/matrix/27b_sft_w4_tp2_dp1_pp2_sp0.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp2_dp1_pp2_sp1 "samples/configs/matrix/27b_sft_w4_tp2_dp1_pp2_sp1.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp2_dp2_pp1_sp0 "samples/configs/matrix/27b_sft_w4_tp2_dp2_pp1_sp0.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp2_dp2_pp1_sp1 "samples/configs/matrix/27b_sft_w4_tp2_dp2_pp1_sp1.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp4_dp1_pp1_sp0 "samples/configs/matrix/27b_sft_w4_tp4_dp1_pp1_sp0.yaml" "0,1,2,3"
run_one 27b_sft_w4_tp4_dp1_pp1_sp1 "samples/configs/matrix/27b_sft_w4_tp4_dp1_pp1_sp1.yaml" "0,1,2,3"

echo "" | tee -a "$SUMMARY"
echo "=== DONE $(date) ===" | tee -a "$SUMMARY"
echo "PASS=$PASS FAIL=$FAIL TIMEOUT=$TIME" | tee -a "$SUMMARY"
